---
title: "Solucionario de Controles"
format: html
editor: visual
jupyter: julia-1.9
---

## Capítulo 15

### Pregunta 1

De acuerdo a lo discutido en la clase y lo leído en el Capitulo 15 del Ross. ¿Por qué razones las empresas hacen juntas extraordinarias de accionistas ? (marcar solo la incorrecta)

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"Con tal de pronunciarse sobre una propuesta de aumento de capital en la empresa.",
"Toma de decisiones respecto a futuras decisiones de la empresa",
"Ser parte de votaciones acumulativas o directas en las mismas juntas.",
"Comprar acciones preferentes con tal de ser dueño de una parte de la compañia. "
]
  answ = 4
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

Solo la última es incorrecta porque esa decisión suele ser tomada por la dirección ejectuvia de la empresa.No suele ser una decisión que requiera el voto de los accionistas.
:::

## Capítulo 20

### Pregunta 1

En la apertura de Osoji, ¿Pudieron colocar todas las acciones?

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"No, ya que las AFPs desistieron y los papeles comprados por ellas tuvieron que ser retirados del mercado.",
"  No, ya que una Normativa de la CMF restringe a ciertos actores a invertir en SpAs ",
"Si, efectivamente completaron el libro de órdenes."
]
  answ = 2
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La primera es falsa porque no es que la AFPs hayan desistido, es porque no pueden hacerlo por temas de normativa, lo que tambíen hace la tercera incorrecta. Luego, solo la segunda es la correcta.
:::

## Capítulo 21

### Pregunta K

El leasing operativo que pretende ofrecer Voltera requiere de:

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"un banco como socio ",
"arriendo de vehículo  ",
"opción de compra ",
"todas son correctas"
]
  answ = 4
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

es por su modelo de negocio que opera de dos formas: a las app de movilidad les ofrecerá un leasing operativo -plan de arriendo con opción de compra- a través de socio como un banco, en tanto los conductores de taxis y colectivos podrán adquirir el auto directamente.

Luego la última alternativa es correcta.
:::

## Capítulo 22

### Pregunta 1

¿Qué razones motivan la intervención cambiaria del Banco?

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"1. Incertidumbre local ",
"2. Depreciación del peso Chileno ",
"3. Generación de distorción en el mercado financiero ",
"4. Definicion de la talasa politica monetaria",
"5. inflacion",
"6. Las alternativas 1,2, y 3 son correctas"
]
  answ = 6
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La 1 es correcta porque esto afecta el tipo de cambio La 2 es correcta porque es el peso chileno puede perder valor desde el punto de vista del tipo de cambio La 3 es correcta porque las distorciónes en el mercado financiero afectan el tipo de cambio La 4 es incorrecta porque la tasa de politica monetaria no afecta el tipo de cambio La 5 es incorrecta porque la inflación corresponde a algo interno del pais, no al tipo de cambio. Luego: la alternativa 6 es la correcta.
:::

## Capítulo 24

### Pregunta 1

Para definir ausencia de arbitraje decimos que si los retornos son positivos, es decir, $$ W \cdot \theta \geqslant 0 $$ entonces el costo del portafolio es negativo

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"falso ",
"verdadero",
]
  answ = 1
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La noción de que un costo es un valor positivo (intuitivamente). Por lo que un costo negativo no es un costo. En efecto es una ganancia.
:::

### Pregunta 2

En el caso de 3 activos y 2 estados de la naturaleza, el resultado de $$ W \cdot \theta$$ es igual a:

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"1. Un vector de dimensión 3, donde la primera componente es el costo del portafolio y las dos componentes restantes son los retornos en cada estado",
"2. Un vector con el promedio ponderado (por el portafolio) de; el valor de los activos, el retorno de los activos en un estado y el retorno de los activos en el otro estado",
"3.Un vector de dimensión 3, retornos en cada estado",
"4.Un vector de dimensión 3, donde la primera componente es el costo del portafolio y las dos componentes restantes son los retornos de cada activo ",
"5. alternativa 1 y 2 correcta"
]
  answ = 5
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La alterantiva 3 es incorrecta porque el vector tambien incluye los costos del portafolio

La alternativa 4 es incorrecta porque el vector es de dimension 3 y si son 3 activos no puede ser de dimension 3 ya que incluye el costo del portafolio

La 1 y 2 son equivalentes y ambas son correctas. Luego la alternativa 5 es correcta.
:::

### Pregunta 3

Cuál de las siguientes razones, NO beneficia la decisión de emitir deuda convertible sobre deuda directa:

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"  Cuando el precio de la acción aumenta después de emitir deuda convertible.",
"Cuando el precio de la acción disminuye después de emitir deuda convertible o no aumenta lo suficiente.",
]
  answ = 1
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La segunda alternativa si beneficia a la firma de emitir deuda convertible, ya que si el precio de las acciones no aumenta significativamente o disminuye tras la emisión de deuda convertible, los dueños del bono convertible pueden sentirse menos inclinados a convertir su deuda en capital. Como resultado, la empresa podría acabar pagando la deuda al vencimiento, tratando esencialmente la deuda convertible como si fuera deuda tradicional.

Luego, la alternativa 1 es la correcta
:::

### Pregunta 4

¿Cuál de las siguientes alternativas, es (son) características de los warrants?

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"1. Son títulos que dan a los tenedores el derecho, aunque no la obligación, de vender acciones.",
"2. Los warrant no especifican el número de acciones que el tenedor puede comprar.",
"3. Los warrant se parecen a las opciones de compra.",
"4. Los warrant por lo general, tienen períodos de vencimientos menor a 30 días "
]
  answ = 3
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta
La 1 es incorrecta porque es comprar, no vender
La 2 es incorrecta porque si espeficia
La 4 es incorracta porque en promedio tienen mucho mayor periodo
Luego la 3 es correcta


:::

### Pregunta 5

Desde el punto de vista de los accionistas, la política óptima de redención sería redimir los convertibles cuando el valor de conversión es mayor al precio de redención.

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"Verdadero",
"Falso"
]
  answ = 2
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

Es falso porque ellos quieren prevenir la dilución y para eso la politica debe ser al revés


:::

## Capítulo 25

### Pregunta 1

Cuál de las siguientes definiciones, concuerda con el de duración.


```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
" La duración es un promedio del vencimiento de los flujos de efectivo del bono, ponderados con base en el valor presente de cada flujo de efectivo. ",
"La duración es una desviación estándar del vencimiento de los flujos de efectivo del bono, ponderados con base en el valor presente de cada flujo de efectivo. ",
"La duración es una suma del vencimiento de los flujos de efectivo del bono, ponderados con base en el valor presente de cada flujo de efectivo.",
"  La duración es una multiplicación del vencimiento de los flujos de efectivo del bono, ponderados con base en el valor presente de cada flujo de efectivo. ",
]
  answ = 1
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

Solo el promedio nos entrega una representacion del tiempo del bono
:::


### Pregunta 2

¿Cuál de las siguientes afirmaciones de los contratos de futuros es verdadera?

I. El vendedor de un contrato de futuros sobre un bono del Tesoro puede decidir efectuar la entrega en cualquier día hábil del mes de entrega,

II. Los contratos de futuro se negocian por lo general en bolsas.

III. Por lo general hay un mercado líquido de contratos de futuros que permite que se puedan liquidar con rapidez.

IV. Los contratos de futuros normalmente dan al vendedor un periodo para entregar

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"I",
"I,II, y III",
"I, III, IV",
"Todas"
]
  answ = 4
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

Todas
I. Esta flexibilidad da al inversor una posibildades de estrategias mas amplias
II.La negociación en bolsa garantiza la estandarización de la compra y venta
III.Poder venderlos y comprarlos rapido es una caracteristica de estos activos
IV. Saber esta flexibilidad es imporante


:::


### Pregunta 3

¿Qué es el interés abierto en un contrato de futuros?

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"Es el número de contratos que se encuentran cerrados al final del día. ",
"Es el número de contratos que se encuentran abiertos al final del día. ",
"Es el interés que genera el contrato de futuro.",
"Ninguna de las anteriores."
]
  answ = 2
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La cantidad de contratos abiertos al final del dia es un indicador para determinar el sentimiento del mercado y la fuerza de la tendencia de los precios.

:::


## Capítulo 26


### Pregunta 1

¿Qué es un depósito en consignación (tipo común de préstamos sobre inventarios, préstamos que usan el inventario como garantía)?

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"El prestatario mantiene inventarios en 'depósito' para el prestamista. El producto de la venta del inventario se remite de inmediato al prestamista.",
"Una garantía general da al prestamista un derecho prendario sobre todos los inventarios del prestatario.",
"Cuando se recurre al financiamiento mediante almacenes generales de depósito, una empresa pública de almacenamiento supervisa el inventario en nombre del prestamista.",
"Son depósitos que la compañía mantiene en el banco en cuentas que pagan intereses bajos o ninguno en absoluto."
]
  answ = 3
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La ultima la alternativa no es la correcta porque esto no tiene relación con cuentas bancarias

La segunda y tercera son otros tipos de prestamos de inventario.

La primera es la correcta. El documento donde se hace constar el 
préstamo se llama depósito en consignación.

:::


## Capítulo 27


### Pregunta 1

Usted tiene una partida de transito de 291 por 17 días. Suponiendo que el mes tiene 31 días. ¿Cuál es el promedio diario de las partidas en tránsito? (Respuesta no debe dar con decimales)


```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
" 17",
"120",
"160"
]
  answ = 3
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta
Es $$   \frac{291 \cdot 17}{31} = 160 $$

:::


## Capítulo 28

### Pregunta 1

¿Por qué el regulador interviene el mercado de asesoría previsional? Elija sólo la principal


```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"Para prevenir que las personas tomen decisiones libremente dentro de alternativas más riesgosas",
"Para prevenir que las personas tomen decisiones libremente dentro de alternativas que provoquen pérdidas en promedio",
"Para limitar la volatilidad y costos en los que incurren las AFP"
]
  answ = 2
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

La primera es incorrecta porque no lo hace para disminuir la libertad personas en relación a las alterntivas mas riesgosas.
La tercera es cierta, pero no es la principal ya que es la segunda: evitar que las personas incurran en pérdidas, es decir, proteger las personas.

:::




## Capítulo 31

### Pregunta 1

Esta pregunta requiere responder una de las alternativas siguientes:

```{julia}
#| hold: true
#| echo: false
using QuizQuestions
lh_choices = [
"tipo de cambio",
"inflacion"
]
  answ = 1
  radioq(lh_choices, answ, keep_order=true)
```

::: {.callout-note collapse="true"}
#### Pauta

El término cubierto se refiere al hecho de que el inversionista está cubierto en caso de que se produzca  una variación del tipo de cambio porque el tipo de cambio a plazo se asegura desde hoy.

:::



